name: CI pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Configurer python
        uses: actions/setup-python@v2
        with:
          python-version:'3.x'
        with: 
          python-version: 3.x
      
      - name: Installer les dependances
        run: |
          pip install pytest
        
      - name: Executer les tests
        run: |
          pytest tests/